# This workflow will  run tests 

name: main

on:
  push:
    branches: [ "new_features_474386" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
        matrix:
          os: [ubuntu-latest, windows-latest]
          python-version: ["3.10"]


    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test with unittest
      run: |
        cd tests
        python -m unittest perimeter_test.py
        python -m unittest area_test.py
