# This workflow will install Python dependencies, run tests 
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "new_features_474386" ]

jobs:
  build:

    runs-on: ubuntu-latest, windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test with unittest
      run: |
        python -m unittest tests/perimeter_test.py
        python -m unittest tests/area_test.py
